CREATE TABLE submittable.business_assistance_service_provider_applications (
    email VARCHAR,
    application_status VARCHAR,
    application_date VARCHAR,
    demographic_info_of_owner VARCHAR,
    demographic_detail VARCHAR,
    business VARCHAR,
    business_address VARCHAR,
    business_address_2 VARCHAR,
    city VARCHAR,
    state VARCHAR,
    zip VARCHAR,
    website VARCHAR,
    title VARCHAR,
    phone VARCHAR,
    public_facing_email VARCHAR,
    legal_business_name VARCHAR,
    organizational_structure VARCHAR,
    how_long_has_your_business_been_in_operation VARCHAR,
    number_of_w2_employees VARCHAR,
    number_of_1099_independent_contractor_employees VARCHAR,
    number_of_subcontractors VARCHAR,
    employer_identification_number_ein VARCHAR
);
